name: Run all tests

on:
  push:
    branches:
    - main
    - stable
  pull_request:
    branches:
    - main
    - stable
  schedule:
    - cron: '0 7 * * *'

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
#       os: [ubuntu-latest, macos-latest] # @todo: macOS need fixes

    steps:
    - uses: actions/checkout@v2

    - uses: sreimers/pr-dependency-action@v0.5
      with:
        name: re
        repo: https://github.com/baresip/re
        secret: ${{ secrets.GITHUB_TOKEN }}

    - uses: sreimers/pr-dependency-action@v0.5
      with:
        name: rem
        repo: https://github.com/baresip/rem
        secret: ${{ secrets.GITHUB_TOKEN }}

    - name: make re/rem
      run: |
        for p in re rem; do
          cmake -S $p -B $p/build
          cmake --build $p/build -j
        done
        for p in re rem; do
          mv $p ../.
        done

    - name: ldconfig
      if: ${{ runner.os == 'Linux' }}
      run: sudo ldconfig

    - name: retest
      run: |
        cmake -DCMAKE_C_FLAGS="-Werror" . && make
        ./retest -a -v
